// prod.js - production keys here

import { EnvironmentVariables } from 'types/keys.config';

const productionKeys: EnvironmentVariables = {
  WALLET_ADDRESS: {
    matic: process.env.WALLET_ADDRESS,
    bsc: process.env.WALLET_ADDRESS_BSC,
  },
  WALLET_PRIVATE_KEY: {
    matic: process.env.WALLET_PRIVATE_KEY,
    bsc: process.env.WALLET_PRIVATE_KEY_BSC,
  },
  WALLET_ADDRESS_ICE_REGISTRANT: {
    matic:
      process.env.NODE_ENV === 'production'
        ? [
            process.env.WALLET_ADDRESS_ICE_REGISTRANT1,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT2,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT3,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT4,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT5,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT6,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT7,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT8,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT9,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT10,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT11,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT12,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT13,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT14,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT15,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT16,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT17,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT18,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT19,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT20,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT21,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT22,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT23,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT24,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT25,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT26,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT27,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT28,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT29,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT30,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT31,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT32,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT33,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT34,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT35,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT36,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT37,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT38,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT39,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT40,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT41,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT42,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT43,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT44,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT45,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT46,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT47,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT48,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT49,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT50,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT51,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT52,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT53,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT54,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT55,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT56,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT57,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT58,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT59,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT60,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT61,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT62,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT63,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT64,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT65,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT66,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT67,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT68,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT69,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT70,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT71,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT72,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT73,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT74,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT75,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT76,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT77,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT78,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT79,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT80,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT81,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT82,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT83,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT84,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT85,
          ]
        : process.env.NODE_ENV === 'staging'
        ? [
            process.env.WALLET_ADDRESS_ICE_REGISTRANT86,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT87,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT88,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT89,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT90,
          ]
        : process.env.NODE_ENV === 'development'
        ? [
            process.env.WALLET_ADDRESS_ICE_REGISTRANT91,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT92,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT93,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT94,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT95,
          ]
        : [
            process.env.WALLET_ADDRESS_ICE_REGISTRANT96,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT97,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT98,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT99,
            process.env.WALLET_ADDRESS_ICE_REGISTRANT100,
          ],
  },
  WALLET_PRIVATE_KEY_ICE_REGISTRANT: {
    matic:
      process.env.NODE_ENV === 'production'
        ? [
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT1,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT2,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT3,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT4,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT5,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT6,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT7,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT8,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT9,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT10,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT11,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT12,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT13,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT14,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT15,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT16,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT17,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT18,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT19,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT20,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT21,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT22,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT23,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT24,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT25,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT26,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT27,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT28,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT29,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT30,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT31,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT32,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT33,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT34,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT35,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT36,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT37,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT38,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT39,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT40,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT41,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT42,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT43,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT44,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT45,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT46,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT47,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT48,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT49,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT50,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT51,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT52,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT53,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT54,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT55,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT56,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT57,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT58,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT59,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT60,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT61,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT62,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT63,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT64,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT65,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT66,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT67,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT68,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT69,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT70,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT71,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT72,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT73,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT74,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT75,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT76,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT77,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT78,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT79,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT80,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT81,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT82,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT83,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT84,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT85,
          ]
        : process.env.NODE_ENV === 'staging'
        ? [
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT86,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT87,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT88,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT89,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT90,
          ]
        : process.env.NODE_ENV === 'development'
        ? [
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT91,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT92,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT93,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT94,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT95,
          ]
        : [
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT96,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT97,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT98,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT99,
            process.env.WALLET_PRIVATE_KEY_ICE_REGISTRANT100,
          ],
  },
  WALLET_ADDRESS_ICE_KEEPER_CLAIM: {
    matic: process.env.WALLET_ADDRESS_ICE_KEEPER_CLAIM,
  },
  WALLET_PRIVATE_KEY_ICE_KEEPER_CLAIM: {
    matic: process.env.WALLET_PRIVATE_KEY_ICE_KEEPER_CLAIM,
  },
  DB_CONNECTION_STRING: process.env.DB_CONNECTION_STRING,
  REDIS_CONNECTION_STRING: process.env.REDIS_CONNECTION_STRING,
  JWT_ACCESS_TOKEN_SECRET: process.env.SHARED_JWT_ACCESS_TOKEN_SECRET,
  SLACK_VERIFY_TOKEN: process.env.SLACK_VERIFY_TOKEN,
  NODE_ENV: process.env.NODE_ENV
};

export default productionKeys;
